name: Makefile CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Get submodules
      run: git submodule update --init --recursive

    - name: Update apt
      run: sudo apt-get update --fix-missing
    
    - name: Install valgrind, libbsd & tree
      run: sudo apt-get install valgrind libbsd-dev tree

    - name: Install norminette
      run: pip install norminette

    - name: Run tree
      run: tree

    - name: Run norminette
      run: norminette src include

    - name: Make libft
      run: make

    - name: Re-make libft
      run: make re

    - name: View Contents of libft
      run: nm -C build/libft.a

    - name: Run tests
      run: make test
