name: Makefile CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Lib
      run: sudo apt-get install libbsd-dev
      
    - name: Get submodules
      run: git submodule update --init --recursive

    - name: Make program
      run: make

    - name: Re-make program
      run: make re

    - name: View Contents of Libft
      run: nm -C build/libft.a

    - name: Run Tests
      run: make test
